//Declare required variables
var upper = 10000;
var randomNumber = getRandomNumber(upper) //Stores number generated by Function
var guess;                                //Stores number generated in loop
var attempts = 0;                         //Stores the number of attempts

// Random number generator function
function getRandomNumber(upper) {
  return Math.floor( Math.random() * upper ) + 1;
}

//Loop evaluates to false when "guess" matches "randomNumber"
while ( guess !== randomNumber ) {
guess = getRandomNumber(upper);
attempts += 1;
}

//Print results
document.write("The number was " + randomNumber + ". ")
document.write("It took the computer " + attempts + " attempts to guess right!")
